- name: bashrc
  hosts: control
  gather_facts: no
  tasks:
    - name: Edit /root/.bashrc
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: "{{ item }}"
        state: present
      loop:
        - "source <(kubectl completion bash)"
        - "export EDITOR=nano"
        - "alias ll='ls -la'"
        - "alias k=kubectl"
        - "complete -F __start_kubectl k"
