---
- name: Install Longhorn
  hosts: all

  tasks:
    - name: Installation Requirements
      apt:
        name:
          - bash
          - curl
          - grep
          - util-linux    # findmnt, lsblk, blkid
          - gawk          # awk
          - open-iscsi
          - nfs-common
          - jq
          - cryptsetup
        state: present

    - name: Enable iscsi_tcp module
      modprobe:
        name: iscsi_tcp
        state: present
