---
- name: Install Longhorn
  hosts: all

  tasks:
    - name: Installation Requirements
      apt:
        name:
          - bash
          - curl
          - grep
          - util-linux    # findmnt, lsblk, blkid
          - gawk          # awk
          - open-iscsi
          - nfs-common
          - jq
          - cryptsetup
        state: present

    - name: Enable kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - iscsi_tcp
        - dm_crypt

    - name: Startup kernel modules
      copy:
        dest: "/etc/modules-load.d/{{ item }}.conf"
        content: "{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - iscsi_tcp
        - dm_crypt
