- name: Prepare /dev/sdb
  hosts: pi1
  gather_facts: no
  tasks:
    - name: 1/5 Mountpoint
      file:
        path: /mnt/data
        state: directory
        mode: '0755'

    - name: 2/5 Partition
      parted:
        label: gpt
        device: /dev/sda
        number: 1
        state: present
        part_start: 10MiB
        part_end: 100%
        align: optimal

    - name: 3/5 Filesystem
      filesystem:
        fstype: ext4
        dev: /dev/sda1

    - name: 4/5 PARTUUID
      command: blkid -s PARTUUID -o value /dev/sda1
      register: partuuid
      changed_when: false

    - name: 5/5 FStab
      mount:
        src: "PARTUUID={{ partuuid.stdout }}"
        path: /mnt/data
        fstype: ext4
        opts: defaults
        state: mounted
