- name: Prepare /dev/sdb
  hosts: control
  tasks:
    - name: 1/5 GPT
      parted:
        device: /dev/sdb
        number: 1
        label: gpt
        state: present

    - name: 2/5 Partition
      parted:
        device: /dev/sdb
        number: 1
        state: present
        part_type: primary
        fs_type: ext4
        part_start: 1MiB
        part_end: 100%

    - name: 2/5 Filesystem
      filesystem:
        fstype: ext4
        dev: /dev/sdb1

    - name: 3/5 Mountpoint
      file:
        path: /mnt/data
        state: directory
        mode: '0755'

    - name: 4/4 FStab
      mount:
        path: /mnt/data
        src: /dev/sdb1
        fstype: ext4
        opts: defaults
        state: mounted
