- name: Prepare /dev/sdb
  hosts: ubuntu
  tasks:

    - name: 1/6 Creaete partition
      command: echo -e "g\nn\n\n\n\nw" | fdisk /dev/sdb
      changed_when: true

    - name: 2/6 Create filesystem
      filesystem:
        fstype: ext4
        dev: /dev/sdb1

    - name: 3/6 Get UUID
      command: blkid -s UUID -o value /dev/sdb1
      register: disk_uuid
      changed_when: false

    - name: 4/6 Create mountpoint
      file:
        path: /mnt/data
        state: directory
        mode: '0755'

    - name: 5/6 Change /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "UUID={{ disk_uuid.stdout }} /mnt/data ext4 defaults 0 2"
        state: present

    - name: 6/6 Mount disk
      command: mount -a
